### ISSUE TITLE
JMX exporter already supports hot update

### ISSUE THREAD

**Issue by cobolbaby** [jianzhiunique/kafka-jmx-exporter#1]

**Comment by zmxckj** [comment]
Thank you for your suggestion. Recently, I didn't pay attention to the changes of exporters, but running exporter with another program will not change.
Because,
1. you can running kafka with yaml and exporter if you like
2. when you deploy exporter on a running kafka, another program need not to restart kafka
3. this program has more work to do, like collect consumer commit offset
